#!/usr/bin/env bash
{ set +x; } 2>/dev/null

usage() {
    echo "usage: $(basename $0)" 1>&2
    [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; exit
}

[[ $1 == "-h" ]] || [[ $1 == "--help" ]] && usage "$@"

[[ $# != 0 ]] && usage

osascript <<EOF | tr , '\n' | sed 's/^[ \t]*//;s/[ \t]*$//'
tell application "System Events" to get the name of every login item
EOF
