#!/usr/bin/env bash
{ set +x; } 2>/dev/null

usage() {
    cat <<EOF 1>&2
usage: $(basename $0) command [args]

Available commands:
    add                    add login items
    list                   print login items names
    paths                  print login items paths
    rm                     remove login items

run \`$(basename $0) COMMAND --help\` for more infos
EOF
    [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; exit
}

[[ $1 == "-h" ]] || [[ $1 == "--help" ]] && usage "$@"

"${BASH_SOURCE[0]%/*}"/."${BASH_SOURCE[0]##*/}"-"$1" "${@:2}"

